### PR TITLE
CLOUDP-269299:  Send changelog summary to slack channel

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Proposed changes

_Jira ticket:_ CLOUDP-269299

This PR defines a GH action to send a slack notification every Monday at 9:00 AM (UTC) with the changes in the cloud-dev changelog.

Screenshot 2024-08-28 at 11 58 10

### CODE REVIEW

**Review by blva — APPROVED** [review]
which channel did we choose?

**Comment by wtrocki** [comment]
@andreaangiolillo Out of the curiosity. Do you have ability to link PRs/github links/commits etc?
If that is possible we do not need to be owners for every API change?
Do you intend for bot to take into account only weeks period (can be configured)?

**Comment by andreaangiolillo** [comment]
Updates:
The PR is waiting for webhook url.

**Comment by andreaangiolillo** [comment]
@wtrocki 
> Out of the curiosity. Do you have ability to link PRs/github links/commits etc?

No, the report is generated by the `changelog.json` which doesn't have PRs/commits information 😢 


> Do you intend for bot to take into account only weeks period (can be configured)?

The GH action runs every Monday at 9:00 AM and can be run manually by providing start and end date. I will document how to run it after the PR is merged and I tested it works as expected.

**Comment by wtrocki** [comment]
Awesome. Thank you for the info.

**Pull request merged**
